# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: Rg141214
                        roles: 'ROLE_ADMIN'
                    niko:
                        password: ganjafarmer
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN }